# Generated by Django 2.0.8 on 2018-08-26 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(verbose_name='when a match is created')),
                ('mode', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('telemetry_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('shard', models.CharField(max_length=10, verbose_name='region')),
                ('kills', models.PositiveSmallIntegerField(default=0)),
                ('deaths', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('gold', models.PositiveSmallIntegerField(default=0)),
                ('farm', models.PositiveSmallIntegerField(default=0)),
                ('items', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=10)),
                ('won', models.BooleanField()),
                ('actor', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vainlab.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('shard', models.CharField(max_length=10, verbose_name='region')),
                ('elo', models.PositiveSmallIntegerField(default=0)),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('last_update_at', models.DateTimeField(default=datetime.datetime(2018, 8, 26, 16, 13, 54, 310947, tzinfo=utc), verbose_name='last time searched for matches')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('team_kill_score', models.PositiveSmallIntegerField(default=0)),
                ('side', models.CharField(max_length=10)),
                ('turret_kill', models.PositiveSmallIntegerField(default=0)),
                ('turret_remain', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vainlab.Match')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vainlab.Player'),
        ),
        migrations.AddField(
            model_name='participant',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vainlab.Roster'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='vainlab.Player'),
        ),
    ]
