# Generated by Django 2.0.5 on 2018-06-30 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vainlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_update_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 3, 25, 5, 402572, tzinfo=utc), verbose_name='last time searched for matches'),
        ),
    ]
