# Generated by Django 2.0.5 on 2018-06-30 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vainlab', '0004_auto_20180630_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_update_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 15, 35, 49, 342344, tzinfo=utc), verbose_name='last time searched for matches'),
        ),
    ]
